2025-02-07 22:57:48,260 [INFO] USER:mamatkasym_mamarasul handlers.py:106:syndicate LOG: Configuration used: C:\Users\mamatkasym_mamarasul\deep-dive-into-serverless\lambda-demo\task01\.syndicate-config-dev
2025-02-07 22:57:48,260 [ERROR] USER:mamatkasym_mamarasul decorators.py:136:wrapper LOG: sdct.conf does not exist inside C:\Users\mamatkasym_mamarasul\deep-dive-into-serverless\lambda-demo\task01\.syndicate-config-dev folder
2025-02-07 22:57:48,262 [ERROR] USER:mamatkasym_mamarasul decorators.py:137:wrapper LOG: Traceback (most recent call last):
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\handlers.py", line 107, in syndicate
    initialize_connection()
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\__init__.py", line 106, in initialize_connection
    CONFIG = ConfigHolder(CONF_PATH)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\conf\processor.py", line 63, in __init__
    self._init_conf_config(dir_path=dir_path)
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\conf\processor.py", line 92, in _init_conf_config
    raise AssertionError(
AssertionError: sdct.conf does not exist inside C:\Users\mamatkasym_mamarasul\deep-dive-into-serverless\lambda-demo\task01\.syndicate-config-dev folder
Traceback (most recent call last):
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\decorators.py", line 134, in wrapper
    return_code = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\handlers.py", line 107, in syndicate
    initialize_connection()
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\__init__.py", line 106, in initialize_connection
    CONFIG = ConfigHolder(CONF_PATH)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\conf\processor.py", line 63, in __init__
    self._init_conf_config(dir_path=dir_path)
  File "C:\Users\mamatkasym_mamarasul\AppData\Local\Programs\Python\Python312\Lib\site-packages\syndicate\core\conf\processor.py", line 92, in _init_conf_config
    raise AssertionError(
AssertionError: sdct.conf does not exist inside C:\Users\mamatkasym_mamarasul\deep-dive-into-serverless\lambda-demo\task01\.syndicate-config-dev folder
